// Mocks generated by Mockito 5.4.6 from annotations
// in kronos/test/features/timer/domain/repositories/timer_repository_contract_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kronos/features/timer/data/source/timer_source.dart' as _i2;
import 'package:kronos/features/timer/domain/entities/timer_entities.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TimerSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimerSource extends _i1.Mock implements _i2.TimerSource {
  @override
  _i3.Future<_i4.TimerSession> startSession({
    required String? subject,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startSession, [], {
              #subject: subject,
              #notes: notes,
            }),
            returnValue: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#startSession, [], {
                  #subject: subject,
                  #notes: notes,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#startSession, [], {
                  #subject: subject,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.TimerSession>);

  @override
  _i3.Future<_i4.TimerSession> pauseSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseSession, [sessionId]),
            returnValue: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#pauseSession, [sessionId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#pauseSession, [sessionId]),
              ),
            ),
          )
          as _i3.Future<_i4.TimerSession>);

  @override
  _i3.Future<_i4.TimerSession> resumeSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeSession, [sessionId]),
            returnValue: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#resumeSession, [sessionId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#resumeSession, [sessionId]),
              ),
            ),
          )
          as _i3.Future<_i4.TimerSession>);

  @override
  _i3.Future<_i4.TimerSession> tickSession({
    required String? sessionId,
    required int? elapsedSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#tickSession, [], {
              #sessionId: sessionId,
              #elapsedSeconds: elapsedSeconds,
            }),
            returnValue: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#tickSession, [], {
                  #sessionId: sessionId,
                  #elapsedSeconds: elapsedSeconds,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.TimerSession>.value(
              _i5.dummyValue<_i4.TimerSession>(
                this,
                Invocation.method(#tickSession, [], {
                  #sessionId: sessionId,
                  #elapsedSeconds: elapsedSeconds,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.TimerSession>);

  @override
  _i3.Future<_i4.TimerSessionSummary> finishSession({
    required String? sessionId,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishSession, [], {
              #sessionId: sessionId,
              #notes: notes,
            }),
            returnValue: _i3.Future<_i4.TimerSessionSummary>.value(
              _i5.dummyValue<_i4.TimerSessionSummary>(
                this,
                Invocation.method(#finishSession, [], {
                  #sessionId: sessionId,
                  #notes: notes,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.TimerSessionSummary>.value(
                  _i5.dummyValue<_i4.TimerSessionSummary>(
                    this,
                    Invocation.method(#finishSession, [], {
                      #sessionId: sessionId,
                      #notes: notes,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.TimerSessionSummary>);

  @override
  _i3.Future<_i4.TimerSessionSummary?> getLastSession() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSession, []),
            returnValue: _i3.Future<_i4.TimerSessionSummary?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i4.TimerSessionSummary?>.value(),
          )
          as _i3.Future<_i4.TimerSessionSummary?>);
}
