// Mocks generated by Mockito 5.4.6 from annotations
// in kronos/test/features/history/domain/repositories/history_repository_contract_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kronos/features/history/data/source/history_source.dart' as _i2;
import 'package:kronos/features/history/domain/entities/history_entities.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HistorySource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistorySource extends _i1.Mock implements _i2.HistorySource {
  @override
  _i3.Future<List<_i4.HistorySession>> getSessions(_i4.HistoryQuery? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [query]),
            returnValue: _i3.Future<List<_i4.HistorySession>>.value(
              <_i4.HistorySession>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.HistorySession>>.value(
                  <_i4.HistorySession>[],
                ),
          )
          as _i3.Future<List<_i4.HistorySession>>);

  @override
  _i3.Future<_i4.HistorySessionDetails> getSessionDetails(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionDetails, [sessionId]),
            returnValue: _i3.Future<_i4.HistorySessionDetails>.value(
              _i5.dummyValue<_i4.HistorySessionDetails>(
                this,
                Invocation.method(#getSessionDetails, [sessionId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.HistorySessionDetails>.value(
                  _i5.dummyValue<_i4.HistorySessionDetails>(
                    this,
                    Invocation.method(#getSessionDetails, [sessionId]),
                  ),
                ),
          )
          as _i3.Future<_i4.HistorySessionDetails>);

  @override
  _i3.Future<void> updateSessionNotes({
    required String? sessionId,
    required String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionNotes, [], {
              #sessionId: sessionId,
              #notes: notes,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
