// Mocks generated by Mockito 5.4.6 from annotations
// in kronos/test/features/config/data/repositories/config_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kronos/features/config/data/source/config_source.dart' as _i2;
import 'package:kronos/features/config/domain/entities/config_entities.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConfigSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigSource extends _i1.Mock implements _i2.ConfigSource {
  @override
  _i3.Future<_i4.GithubToken?> getSavedToken() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedToken, []),
            returnValue: _i3.Future<_i4.GithubToken?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.GithubToken?>.value(),
          )
          as _i3.Future<_i4.GithubToken?>);

  @override
  _i3.Future<void> saveToken(_i4.GithubToken? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.TokenValidationResult> validateToken(_i4.GithubToken? token) =>
      (super.noSuchMethod(
            Invocation.method(#validateToken, [token]),
            returnValue: _i3.Future<_i4.TokenValidationResult>.value(
              _i5.dummyValue<_i4.TokenValidationResult>(
                this,
                Invocation.method(#validateToken, [token]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.TokenValidationResult>.value(
                  _i5.dummyValue<_i4.TokenValidationResult>(
                    this,
                    Invocation.method(#validateToken, [token]),
                  ),
                ),
          )
          as _i3.Future<_i4.TokenValidationResult>);

  @override
  _i3.Future<_i4.SyncResult> syncPendingSessions() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingSessions, []),
            returnValue: _i3.Future<_i4.SyncResult>.value(
              _i5.dummyValue<_i4.SyncResult>(
                this,
                Invocation.method(#syncPendingSessions, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.SyncResult>.value(
              _i5.dummyValue<_i4.SyncResult>(
                this,
                Invocation.method(#syncPendingSessions, []),
              ),
            ),
          )
          as _i3.Future<_i4.SyncResult>);
}
