// Mocks generated by Mockito 5.4.6 from annotations
// in kronos/test/features/home/domain/repositories/home_repository_contract_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kronos/features/home/data/source/home_source.dart' as _i2;
import 'package:kronos/features/home/domain/entities/home_entities.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeSource extends _i1.Mock implements _i2.HomeSource {
  @override
  _i3.Future<_i4.HomeDashboard> getDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, []),
            returnValue: _i3.Future<_i4.HomeDashboard>.value(
              _i5.dummyValue<_i4.HomeDashboard>(
                this,
                Invocation.method(#getDashboard, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.HomeDashboard>.value(
              _i5.dummyValue<_i4.HomeDashboard>(
                this,
                Invocation.method(#getDashboard, []),
              ),
            ),
          )
          as _i3.Future<_i4.HomeDashboard>);

  @override
  _i3.Future<_i4.HomeDashboard> refreshDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#refreshDashboard, []),
            returnValue: _i3.Future<_i4.HomeDashboard>.value(
              _i5.dummyValue<_i4.HomeDashboard>(
                this,
                Invocation.method(#refreshDashboard, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.HomeDashboard>.value(
              _i5.dummyValue<_i4.HomeDashboard>(
                this,
                Invocation.method(#refreshDashboard, []),
              ),
            ),
          )
          as _i3.Future<_i4.HomeDashboard>);

  @override
  _i3.Future<_i4.HomeSyncStatus> getSyncStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncStatus, []),
            returnValue: _i3.Future<_i4.HomeSyncStatus>.value(
              _i4.HomeSyncStatus.synced,
            ),
            returnValueForMissingStub: _i3.Future<_i4.HomeSyncStatus>.value(
              _i4.HomeSyncStatus.synced,
            ),
          )
          as _i3.Future<_i4.HomeSyncStatus>);
}
